databases:
  - name: pofolback
    databaseName: pofolback
    user: pofolback
    region: singapore
    plan: free

services:
  - type: web
    name: pofolback
    env: python
    region: singapore
    rootDir: backend
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pofolback
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
