# Generated by Django 4.2.1 on 2023-07-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('commonmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonmodel')),
                ('key', models.PositiveIntegerField(unique=True)),
                ('country_code', models.CharField(max_length=5)),
                ('country_localized_name', models.CharField(max_length=200)),
                ('localized_name', models.CharField(max_length=200)),
                ('temperature_value', models.CharField(max_length=200)),
                ('latitude', models.FloatField(max_length=10)),
                ('longitude', models.FloatField(max_length=10)),
            ],
            bases=('common.commonmodel',),
        ),
    ]
