# Generated by Django 4.2.1 on 2023-07-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weathers', '0002_alter_weather_latitude_alter_weather_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='temperature_value',
            field=models.FloatField(max_length=20),
        ),
    ]
